### ISSUE TITLE
Morning Session discussion

### ISSUE THREAD

**Issue by tarikbouari** [ChaabaneAnas/To-do-List#11]
# Hi @ChaabaneAnas 👋  ,
 you have done a great job so far . Here are some changes you can make to your project in order to improve It 

https://github.com/ChaabaneAnas/To-do-List/blob/2f94b2c6aea25d6ba0934ba59da107b7804ebfc1/src/index.js#L46-L51

- I kindly suggest you should add " document.location.reload() " function to refresh the page to fix the bug with the clean all function.

## Happy coding 💻 🥳

**Comment by im-ghost** [comment]
A pull request might be appreciated
